# _config.yml
title: Nasir Abubakar
description: Data Scientist & Economist â€“ Oxford, UK
theme: minima
markdown: kramdown
permalink: pretty

# No navigation links at all
header_pages: []

minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/Nas365" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/nasabu" }

plugins:
  - jekyll-feed

# Hide default header/footer completely
exclude:
  - Gemfile
  - Gemfile.lock