title: Nasir Abubakar
description: Everyday Economics — applied data science projects
theme: minima
markdown: kramdown
permalink: pretty

# Keep header simple (Home only). We’ll use one rich landing page.
header_pages: []

minima:
  skin: classic
  social_links:
    - { platform: github,   user_url: "https://github.com/Nas365" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/nasabu" }

plugins:
  - jekyll-feed
