title: Nasir Abubakar
description: Everyday Economics â€” applied data science projects
theme: minima
markdown: kramdown
permalink: pretty

minima:
  skin: classic
  # Minima shows social links only if you add them here
  social_links:
    - { platform: github,   user_url: "https://github.com/Nas365" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/nasabu" }

# plugins that work on GitHub Pages
plugins:
  - jekyll-feed
