title: Nasir Abubakar
description: Data Scientist & Economist
theme: minima
markdown: kramdown
permalink: pretty

# No header menu â€“ we build one hero landing instead
header_pages: []

minima:
  skin: classic
  social_links:
    - { platform: github,   user_url: "https://github.com/Nas365" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/nasabu" }

plugins:
  - jekyll-feed
